name: openiothub_plugin
description: openiothub_plugin
version: 1.0.2+7
homepage: https://github.com/OpenIoTHub

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.1.0
  #  app内嵌网页浏览器
  flutter_vlc_player: ^7.4.0
  webview_flutter: ^4.2.1
  #  打开url
  url_launcher: ^6.1.11
  #  数据存储
  shared_preferences: ^2.1.1
  #  颜色选择器
  flutter_colorpicker: ^1.0.3
#  fluttertoast: ^8.0.8
  file_picker: ^5.3.0
  filesystem_picker: ^3.1.0
  path_provider: ^2.0.2
  dio: ^5.1.2
  openiothub_constants: ^1.0.0
  openiothub_api: ^1.0.2+1
  openiothub_grpc_api: ^1.0.0
#  gateway_grpc_api: ^1.0.0
#  iot_manager_grpc_api: ^1.0.0

  mqtt5_client: ^4.0.2
  flutter_seekbar: ^1.0.0
  oktoast: ^3.3.2+1
#  ssh
  xterm: ^4.0.0
  dartssh2: ^2.5.0
#  aria2
  aria2_dart: ^0.0.2
  cupertino_icons: ^1.0.6
  dd_js_util: ^6.1.7
  provider: ^6.1.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true